sudo: required
services:
  - docker

before_install:
  - docker build -t suradidchao/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run suradidchao/react-test npm test -- --coverage

after_success:
  - docker build -t chillshyld/multi-client -f ./client
  - docker build -t chillshyld/muti-nginx -f ./nginx
  - docker build -t chillshyld/multi-server -f ./server
  - docker build -t chillshyld/multi-worker -f ./worker
  # Login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push chillshyld/multi-client
  - docker push chillshyld/multi-nginx
  - docker push chillshyld/multi-server
  - docker push chillshyld/multi-worker